//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.26 at 10:24:17 pm EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://husseinabdallah.com/britam", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.husseinabdallah.britam;
