//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 02:58:28 pm EAT 
//


package com.husseinabdallah.jubileeclaim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FacilityList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacilityList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActisureEntity" type="{http://husseinabdallah.com/jubileeClaim}ActisureEntity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacilityList", propOrder = {
    "actisureEntity"
})
public class FacilityList {

    @XmlElement(name = "ActisureEntity", required = true)
    protected ActisureEntity actisureEntity;

    /**
     * Gets the value of the actisureEntity property.
     * 
     * @return
     *     possible object is
     *     {@link ActisureEntity }
     *     
     */
    public ActisureEntity getActisureEntity() {
        return actisureEntity;
    }

    /**
     * Sets the value of the actisureEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActisureEntity }
     *     
     */
    public void setActisureEntity(ActisureEntity value) {
        this.actisureEntity = value;
    }

}
