//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 02:58:28 pm EAT 
//


package com.husseinabdallah.jubileeclaim;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.husseinabdallah.jubileeclaim package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.husseinabdallah.jubileeclaim
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceLines }
     * 
     */
    public InvoiceLines createInvoiceLines() {
        return new InvoiceLines();
    }

    /**
     * Create an instance of {@link Payee }
     * 
     */
    public Payee createPayee() {
        return new Payee();
    }

    /**
     * Create an instance of {@link Beneficiary }
     * 
     */
    public Beneficiary createBeneficiary() {
        return new Beneficiary();
    }

    /**
     * Create an instance of {@link GetClaimDetailsRequest }
     * 
     */
    public GetClaimDetailsRequest createGetClaimDetailsRequest() {
        return new GetClaimDetailsRequest();
    }

    /**
     * Create an instance of {@link LoadClaimRequestMessage }
     * 
     */
    public LoadClaimRequestMessage createLoadClaimRequestMessage() {
        return new LoadClaimRequestMessage();
    }

    /**
     * Create an instance of {@link LoadClaimRequest }
     * 
     */
    public LoadClaimRequest createLoadClaimRequest() {
        return new LoadClaimRequest();
    }

    /**
     * Create an instance of {@link FacilityList }
     * 
     */
    public FacilityList createFacilityList() {
        return new FacilityList();
    }

    /**
     * Create an instance of {@link ActisureEntity }
     * 
     */
    public ActisureEntity createActisureEntity() {
        return new ActisureEntity();
    }

    /**
     * Create an instance of {@link Claim }
     * 
     */
    public Claim createClaim() {
        return new Claim();
    }

    /**
     * Create an instance of {@link Treatment }
     * 
     */
    public Treatment createTreatment() {
        return new Treatment();
    }

    /**
     * Create an instance of {@link InvoiceFrom }
     * 
     */
    public InvoiceFrom createInvoiceFrom() {
        return new InvoiceFrom();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link Invoices }
     * 
     */
    public Invoices createInvoices() {
        return new Invoices();
    }

    /**
     * Create an instance of {@link InvoiceLine }
     * 
     */
    public InvoiceLine createInvoiceLine() {
        return new InvoiceLine();
    }

    /**
     * Create an instance of {@link Treatments }
     * 
     */
    public Treatments createTreatments() {
        return new Treatments();
    }

}
