//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.26 at 10:24:17 pm EAT 
//


package com.husseinabdallah.jubileeclaim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Treatment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Treatment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcedureCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TreatmentStatus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FacilityList" type="{http://husseinabdallah.com/jubileeClaim}FacilityList"/>
 *         &lt;element name="Invoices" type="{http://husseinabdallah.com/jubileeClaim}Invoices"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Treatment", propOrder = {
    "procedureCode",
    "treatmentStatus",
    "facilityList",
    "invoices"
})
public class Treatment {

    @XmlElement(name = "ProcedureCode")
    protected int procedureCode;
    @XmlElement(name = "TreatmentStatus")
    protected int treatmentStatus;
    @XmlElement(name = "FacilityList", required = true)
    protected FacilityList facilityList;
    @XmlElement(name = "Invoices", required = true)
    protected Invoices invoices;

    /**
     * Gets the value of the procedureCode property.
     * 
     */
    public int getProcedureCode() {
        return procedureCode;
    }

    /**
     * Sets the value of the procedureCode property.
     * 
     */
    public void setProcedureCode(int value) {
        this.procedureCode = value;
    }

    /**
     * Gets the value of the treatmentStatus property.
     * 
     */
    public int getTreatmentStatus() {
        return treatmentStatus;
    }

    /**
     * Sets the value of the treatmentStatus property.
     * 
     */
    public void setTreatmentStatus(int value) {
        this.treatmentStatus = value;
    }

    /**
     * Gets the value of the facilityList property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityList }
     *     
     */
    public FacilityList getFacilityList() {
        return facilityList;
    }

    /**
     * Sets the value of the facilityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityList }
     *     
     */
    public void setFacilityList(FacilityList value) {
        this.facilityList = value;
    }

    /**
     * Gets the value of the invoices property.
     * 
     * @return
     *     possible object is
     *     {@link Invoices }
     *     
     */
    public Invoices getInvoices() {
        return invoices;
    }

    /**
     * Sets the value of the invoices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoices }
     *     
     */
    public void setInvoices(Invoices value) {
        this.invoices = value;
    }

}
